openapi: '3.0.3'
info:
  title: Kasir API
  description: Simple POS (Point of Sale) API for managing products, categories, and transactions
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /health:
    get:
      summary: Health check
      description: Check if API is running
      tags:
        - Health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  message:
                    type: string
                    example: API Running

  /api/categories:
    get:
      summary: Get all categories
      description: Retrieve list of all categories. Supports search by name.
      tags:
        - Categories
      parameters:
        - name: name
          in: query
          description: Filter categories by name (partial match)
          required: false
          schema:
            type: string
            example: snack
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    
    post:
      summary: Create category
      description: Create a new category
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: Beverages
                description:
                  type: string
                  example: Soft drinks, juices, and coffee
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Invalid request

  /api/categories/{id}:
    get:
      summary: Get category by ID
      description: Retrieve a specific category by ID
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Category ID
          example: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Category not found
    
    put:
      summary: Update category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '200':
          description: Category updated successfully
    
    delete:
      summary: Delete category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Category deleted successfully

  /api/products:
    get:
      summary: Get all products
      description: Retrieve list of all products. Supports search by name.
      tags:
        - Products
      parameters:
        - name: name
          in: query
          description: Filter products by name (partial match)
          required: false
          schema:
            type: string
            example: cola
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    
    post:
      summary: Create product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - price
                - stock
                - category_id
              properties:
                name:
                  type: string
                  example: Coca Cola 500ml
                price:
                  type: number
                  example: 7500
                stock:
                  type: integer
                  example: 50
                category_id:
                  type: integer
                  example: 2
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'

  /api/products/{id}:
    get:
      summary: Get product by ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    
    put:
      summary: Update product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: { type: string }
                price: { type: number }
                stock: { type: integer }
                category_id: { type: integer }
      responses:
        '200':
          description: Product updated successfully
    
    delete:
      summary: Delete product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: Product deleted successfully

  # ===========================
  # TRANSACTIONS
  # ===========================
  /api/checkout:
    post:
      summary: Checkout Transaction
      description: Process a new transaction with multiple items
      tags:
        - Transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutRequest'
      responses:
        '200':
          description: Transaction successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transaction'
        '500':
          description: Internal Server Error (Stock insufficient, etc)

  /api/report/sales-summary:
    get:
      summary: Get Sales Summary
      description: Get revenue, total transactions, and best seller item.
      tags:
        - Reports
      parameters:
        - name: start_date
          in: query
          description: Start Date (Format YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date
            example: 2026-01-01
        - name: end_date
          in: query
          description: End Date (Format YYYY-MM-DD)
          required: false
          schema:
            type: string
            format: date
            example: 2026-02-01
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SalesSummary'

components:
  schemas:
    # --- Category Schemas ---
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Food
        description:
          type: string
          example: Snack and Meals
    
    # --- Product Schemas ---
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Indomie Godog
        price:
          type: number
          example: 3500
        stock:
          type: integer
          example: 10
        category_id:
          type: integer
          example: 1
        category:
          $ref: '#/components/schemas/Category'

    # --- Transaction Schemas ---
    CheckoutRequest:
      type: object
      properties:
        items:
          type: array
          items:
            type: object
            properties:
              product_id:
                type: integer
                example: 2
              quantity:
                type: integer
                example: 5

    Transaction:
      type: object
      properties:
        id:
          type: integer
          example: 101
        total_amount:
          type: integer
          example: 50000
        created_at:
          type: string
          format: date-time
        details:
          type: array
          items:
            $ref: '#/components/schemas/TransactionDetail'

    TransactionDetail:
      type: object
      properties:
        id:
          type: integer
        product_id:
          type: integer
        product_name:
          type: string
        quantity:
          type: integer
        subtotal:
          type: integer

    # --- Report Schemas ---
    SalesSummary:
      type: object
      properties:
        total_revenue:
          type: integer
          example: 150000
        total_transactions:
          type: integer
          example: 12
        best_seller:
          type: object
          properties:
            name:
              type: string
              example: "Indomie Goreng"
            qty_sold:
              type: integer
              example: 50

tags:
  - name: Health
    description: Health check endpoints
  - name: Categories
    description: Category management
  - name: Products
    description: Product management
  - name: Transactions
    description: Checkout and Order processing
  - name: Reports
    description: Sales analytics