openapi: '3.0.3'
info:
  title: Kasir API
  description: Simple POS (Point of Sale) API for managing products and categories
  version: '1.0'
servers:
  - url: http://localhost:8080
    description: Local development server

paths:
  /health:
    get:
      summary: Health check
      description: Check if API is running
      tags:
        - Health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: OK
                  message:
                    type: string
                    example: API Running

  /api/categories:
    get:
      summary: Get all categories
      description: Retrieve list of all categories
      tags:
        - Categories
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    
    post:
      summary: Create category
      description: Create a new category
      tags:
        - Categories
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  example: Electronics
                description:
                  type: string
                  example: Electronic devices and gadgets
      responses:
        '201':
          description: Category created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Invalid request

  /api/categories/{id}:
    get:
      summary: Get category by ID
      description: Retrieve a specific category by ID
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Category ID
          example: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Invalid Category ID
        '404':
          description: Category not found
    
    put:
      summary: Update category
      description: Update an existing category
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Category ID
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Food & Beverage
                description:
                  type: string
                  example: All food and drink items
      responses:
        '200':
          description: Category updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '400':
          description: Invalid request
        '404':
          description: Category not found
    
    delete:
      summary: Delete category
      description: Delete a category by ID
      tags:
        - Categories
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Category ID
          example: 1
      responses:
        '200':
          description: Category deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category deleted successfully
        '400':
          description: Invalid Category ID
        '404':
          description: Category not found

  /api/products:
    get:
      summary: Get all products
      description: Retrieve list of all products
      tags:
        - Products
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    
    post:
      summary: Create product
      description: Create a new product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - price
                - stock
                - category_id
              properties:
                name:
                  type: string
                  example: Coca Cola 330ml
                price:
                  type: number
                  example: 5000
                stock:
                  type: integer
                  example: 100
                category_id:
                  type: integer
                  example: 2
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid request or Category ID not found

  /api/products/{id}:
    get:
      summary: Get product by ID
      description: Retrieve a specific product by ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Product ID
          example: 1
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid product ID
        '404':
          description: Product not found
    
    put:
      summary: Update product
      description: Update an existing product
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Product ID
          example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Indomie Goreng Special
                price:
                  type: number
                  example: 4000
                stock:
                  type: integer
                  example: 50
                category_id:
                  type: integer
                  example: 1
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Invalid request or Category ID not found
        '404':
          description: Product not found
    
    delete:
      summary: Delete product
      description: Delete a product by ID
      tags:
        - Products
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: Product ID
          example: 1
      responses:
        '200':
          description: Product deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Product deleted successfully
        '400':
          description: Invalid product ID
        '404':
          description: Product not found

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Food
        description:
          type: string
          example: Snack and Meals
    
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Indomie Godog
        price:
          type: number
          example: 3500
        stock:
          type: integer
          example: 10
        category_id:
          type: integer
          example: 1

tags:
  - name: Health
    description: Health check endpoints
  - name: Categories
    description: Category management
  - name: Products
    description: Product management